### ISSUE TITLE
gpscorrelate messes exif data from Sony arw files

### ISSUE THREAD

**Issue by malenki** [freefoote/gpscorrelate#1]
After correlating .arw files with a gpx file using this command line
`gpscorrelate -tMvz +2 -g file.gpx ./*arw`
exiftool sais for the files created:
`exiftool "-DateTimeOriginal+=0:0:0 0:0:1" *.arw
Warning: Bad format (12592) for SR2Private entry 0 - dscRX014379.arw
Error: Error writing MakerNotes - dscRX014379.arw`
Even with the switch -m of exiftool it won't modify those files anymore.

**Comment by jat255** [comment]
Was an issue ever raised about this the `exiv2` team? I have just run into what I believe is the same bug.
