### ISSUE TITLE
exif-gps.cpp: bad catch type ?

### ISSUE THREAD

**Issue by dcb314** [freefoote/gpscorrelate#3]
exif-gps.cpp:94:24: warning: catching polymorphic type 'Exiv2::Error {aka class Exiv2::BasicError<char>}' by value [-Wcatch-value=]

Source code is

    } catch (Exiv2::Error e) {

Maybe better code

    } catch (const Exiv2::Error & e) {

Duplicates:

exif-gps.cpp:157:
exif-gps.cpp:296:
exif-gps.cpp:452:
exif-gps.cpp:667:
exif-gps.cpp:744:

**Comment by dfandrich** [comment]
Note that development of gpscorrelate has moved to https://github.com/dfandrich/gpscorrelate  This issue was fixed in the 2.0 release.
